### ISSUE TITLE
Plugin wipes shops config file if edited and reloaded during uptime.

### ISSUE THREAD

**Issue by LaposLazulia** [SirLeezus/OneStopShop#14]
Tried to remove/edit the fly command (Shop item) ingame, but that's not possible so I edited the config to change pricing etc. 

I reload the plugin and it works.

Later i edit the config again to remove and reprice  things from catagories and reload the plugin. 

Everything is gone. 

I check the shop, everything is gone. Every catagory just has dirt now. 

I had a backup so I stop the server, replace the shops config and start the server. 

Nope. The plugin resets the shop to nothing but 1 dirt in each catagory. 

My guess is that it doesn't like there being no items in a certain catagory? 

It was fine earlier though. This needs looked into...

**Comment by LeeTheTech** [comment]
I would need your config files and any errors that came up during this process to look into this issue, sounds like a yml format issue.

**Comment by LaposLazulia** [comment]
Here's the config I changed
https://drive.google.com/file/d/1UDmsnaUecj7-wNKDc73IwLPGCfMi99qW/view?usp=drivesdk

**Comment by LeeTheTech** [comment]
Yeah, that had quite a few yml errors, the console will tell you the exact line you have an issue on, here is a fixed version: https://drive.google.com/file/d/1QXVZlHjJRUpMxv4peRFdMAGWda-PqfLb/view?usp=sharing

**Comment by LaposLazulia** [comment]
I don't have access to that file, but thanks for being so quick 😁

**Comment by LeeTheTech** [comment]
Not an issue, the link should also work now!
