### ISSUE TITLE
Order of menus popping up

### ISSUE THREAD

**Issue by SmubsIRL** [SirLeezus/OneStopShop#16]
So i've been struggling with making a new sub menu with your onestopshop plugin (great plugin all around) and I finally got it to work. But i've found that /shop now opens the new submenu i made instead of the original 1st menu. This seems like a silly thing to submit a ticket for but i'm genuinely baffled as to where to go from here, since the code technically worked, but now it just skips my main menu and goes to the sub menu.

**Comment by LeeTheTech** [comment]
Make sure one menu has `main-menu: true` and it should select the menu you want with /shop.
