### ISSUE TITLE
Compatiblity with papermc

### ISSUE THREAD

**Issue by FierraCodes** [SirLeezus/OneStopShop#19]
the plugin cant run on paper for sum reason;-; fix it pls
logs: https://mclo.gs/uOjohb0#L129

**Comment by SirLeezus** [comment]
I've tested this on purpur and paper many times, works perfectly. What issues or errors are you getting?

**Comment by LeeTheTech** [comment]
Should work perfectly with paper, your link throws a 404, please reply with the errors you're getting.

**Comment by FierraCodes** [comment]
sorry, the link was meant to link to the logs but it was deleted
