### ISSUE TITLE
Adding specific items to shop causes issues

### ISSUE THREAD

**Issue by ZackyTeddy** [SirLeezus/OneStopShop#20]
Hi, Im not sure if this has been brought up before but I have been trying to figure out why I cannot add crossbows in. I have tried them loaded and unloaded. If I try to restart the server with the internal command error, it will disable the plugin. I have provided the command I input and the console output below. Would greatly appreciate your help!

![image](https://user-images.githubusercontent.com/58039470/127037400-71a30553-028a-41bb-92e4-2e4d295f4ad2.png)
![image](https://user-images.githubusercontent.com/58039470/127037546-6b70c20a-0d03-4c3d-b95a-32f323d6d102.png)
![image](https://user-images.githubusercontent.com/58039470/127037599-73e1022c-52f7-410a-b1d0-b7ab30deecb3.png)
![image](https://user-images.githubusercontent.com/58039470/127037664-ac47f2a7-493a-4e44-a702-cc2859f37ad6.png)

Oh and uh, trying to add other legitimate items after that ends up with the same "internal command error" error too

It does for some reason still add it onto the shops.yml file.
![image](https://user-images.githubusercontent.com/58039470/127038289-e1e282a7-79f3-4134-8059-4eee475ea510.png)

But like I mentioned before, after a server restart, I cant access the shop anymore. Hope you can help!

**Comment by ZackyTeddy** [comment]
Oh and uh, trying to add other legitimate items ends up with the same error too

**Comment by ZackyTeddy** [comment]
Another update: Bucket of Tropical Fish also causes the issue

**Comment by ZackyTeddy** [comment]
Similarly, firework stars that have dyes tied to them or are small/ large balls also seem to create an issue where they don't save as separate coloured firework stars but it says it was added to the shop
![image](https://user-images.githubusercontent.com/58039470/127179820-4cde5246-a40f-4300-88b1-f5ed446da8a1.png)

**Comment by LeeTheTech** [comment]
Thanks for reporting this, it's an issue with the XSeries API which I fixed in 1.16 but when I updated everything to 1.17 I forgot to fix them again, should have those issues resolved soon.

**Comment by LeeTheTech** [comment]
Try 1.1.8, should fix all these issues.

**Comment by ZackyTeddy** [comment]
Just managed to update the plugin. It still seems empty crossbows cause the same error. Tropical fish and loaded crossbows work now as intended. Thanks for this!

**Comment by LeeTheTech** [comment]
Should be fixed now! :)

**Comment by ZackyTeddy** [comment]
Hi, still relating to this topic, I cant seem to add enchanted books generated by other plugins  into the shop. Gives me the good ol' Internal error occured performing this action. Is this intentional so that the shops only sell vanilla items with little NBT data?

**Comment by LeeTheTech** [comment]
It's likely because the API I use (XSeries) doesn't know the custom enchantment, to fix something like that I would need to switch over to something like nbt-api which I want to do but haven't had the time to do it yet. It would require remaking the plugin basically.
