### ISSUE TITLE
[Feature Request] - Adding lores to display prices in main gui

### ISSUE THREAD

**Issue by ghost** [SirLeezus/OneStopShop#3]
Hey there, I'd love to see a new feature added which would be 
display_lore: 
- "Buy item for X"
- "Sell item for X"
- 
![image](https://user-images.githubusercontent.com/47482523/108434529-188c6d00-7248-11eb-9882-a2e0f85a1265.png)
So that the lore would show up there in the global item gui instead of having to click on it another time

**Comment by LeeTheTech** [comment]
If the item itself has a lore it should display it. But if you're looking for a cosmetic lore that's not currently a option.

**Comment by ghost** [comment]
It shouldn't be that hard to add this right? Can I pay you 10 bucks to add this?

There's no other plugin that works with the plugins I have implemented on my server

**Comment by LeeTheTech** [comment]
No, wouldn't be hard I just don't have time to work on that plugin at the moment.
