### ISSUE TITLE
2 decimal place display in item buy / sell gui

### ISSUE THREAD

**Issue by Lucas-R-Ross** [SirLeezus/OneStopShop#4]
Having trouble getting money prices to format with 2 decimal places for values ending in zero - for instance 0.35 will display correctly as $0.35 but 1.20 will display as $1.2

Wondering if there's a config trick I'm missing to get it to always show prices with 2 decimal places

**Comment by LeeTheTech** [comment]
In the config.yml change `ValueFormat: '#,###'` to `ValueFormat: '#,###.00'` and restart.
