### ISSUE TITLE
Shop issue/idea

### ISSUE THREAD

**Issue by Billyxxdd** [SirLeezus/OneStopShop#5]
Hi is there any option to toggle specifie group that can open for example category called VIP ? Cuz I'm using your plugin and I'd be pleased if you'll add groups that only some players can access. I mean like if you use /kit VIP it will say that you don't have permission but VIP player can do /kit VIP. It would be great if it will work for this plugin. IF you're interested in doing this please do it fast thank you

**Comment by LeeTheTech** [comment]
Currently the menus don't have a perm system but that is something I can add later. I'm working on a recode for this plugin so I'll add it to my TODOs. I have no eta yet, it's a large plugin and I'm currently working on about 5 others but those should be done soon.
